### PR TITLE
Synchronize warming the reflection cache

### LINKED ISSUE #231: Kotlin Reflect ConcurrentModificationException
@BenSchwab @elihart @rossbacher Our crash reporting has reported a rare crash inside of Kotlin reflect. I've never seen anything like this before. Any ideas what might cause something like this?
```
java.util.ConcurrentModificationException: null
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
    at java.util.HashMap$KeyIterator.next(HashMap.java:814)
    at java.util.jar.JarVerifier.readCertificates(JarVerifier.java:266)
    at java.util.jar.JarFile.getInputStream(JarFile.java:380)
    at libcore.net.url.JarURLConnectionImpl.getInputStream(JarURLConnectionImpl.java:222)
    at java.net.URL.openStream(URL.java:470)
    at java.util.ServiceLoader$ServiceIterator.readClass(ServiceLoader.java:224)
    at java.util.ServiceLoader$ServiceIterator.hasNext(ServiceLoader.java:202)
    at kotlin.collections.CollectionsKt___CollectionsKt.firstOrNull(_Collections.kt:220)
    at kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader$Companion$Instance$2.invoke(BuiltInsLoader.kt:39)
    at kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader$Companion$Instance$2.invoke(BuiltInsLoader.kt:36)
    at kotlin.SafePublicationLazyImpl.getValue(LazyJVM.kt:107)
    at kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader$Companion.getInstance(BuiltInsLoader.kt)
    at kotlin.reflect.jvm.internal.impl.builtins.KotlinBuiltIns.createBuiltInsModule(KotlinBuiltIns.java:127)
    at kotlin.reflect.jvm.internal.impl.builtins.jvm.JvmBuiltIns.<init>(JvmBuiltIns.kt:43)
    at kotlin.reflect.jvm.internal.impl.builtins.jvm.JvmBuiltIns.<init>(JvmBuiltIns.kt:18)
    at kotlin.reflect.jvm.internal.components.RuntimeModuleData$Companion.create(RuntimeModuleData.kt:58)
    at kotlin.reflect.jvm.internal.ModuleByClassLoaderKt.getOrCreateModule(moduleByClassLoader.kt:58)
    at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:37)
    at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:34)
    at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
    at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
    at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data.getModuleData(KDeclarationContainerImpl.kt)
    at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:47)
    at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:44)
    at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
    at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
    at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(KClassImpl.kt)
    at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:179)
    at kotlin.reflect.jvm.internal.KClassImpl.getConstructorDescriptors(KClassImpl.kt:196)
    at kotlin.reflect.jvm.internal.KClassImpl$Data$constructors$2.invoke(KClassImpl.kt:91)
    at kotlin.reflect.jvm.internal.KClassImpl$Data$constructors$2.invoke(KClassImpl.kt:44)
    at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
    at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
    at kotlin.reflect.jvm.internal.KClassImpl$Data.getConstructors(KClassImpl.kt)
    at kotlin.reflect.jvm.internal.KClassImpl.getConstructors(KClassImpl.kt:235)
    at kotlin.reflect.full.KClasses.getPrimaryConstructor(KClasses.kt:40)
    at com.airbnb.mvrx.BaseMvRxViewModel$1.call(BaseMvRxViewModel.kt:47)
    at com.airbnb.mvrx.BaseMvRxViewModel$1.call(BaseMvRxViewModel.kt:28)
    at io.reactivex.internal.operators.completable.CompletableFromCallable.subscribeActual(CompletableFromCallable.java:35)
    at io.reactivex.Completable.subscribe(Completable.java:2171)
    at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
    at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
    at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
```

### PR DESCRIPTION
**Pull request by gpeal**
In addition, we should have been checking for `KVisibility == PUBLIC` not `isAccessible`. As is, the second part of the reflection warming was filtering out all properties.

Here is a benchmark in which I switched from FlowViewModel in which I added 80 `@PersistState` properties to another app and back several times with background processes turned off
without `declaredMemberProperties` warming:
```
06-14 08:05:05.240  5295  5344 D Gabe    : persistState: 21
06-14 08:05:05.308  5295  5295 D Gabe    : persistState: 7
06-14 08:05:09.341  5390  5431 D Gabe    : persistState: 32
06-14 08:05:12.328  5390  5390 D Gabe    : persistState: 7
06-14 08:05:16.948  5484  5517 D Gabe    : persistState: 28
06-14 08:05:19.604  5484  5484 D Gabe    : persistState: 4
06-14 08:05:24.098  5569  5599 D Gabe    : persistState: 37
06-14 08:05:24.568  5569  5569 D Gabe    : persistState: 5
06-14 08:05:28.866  5652  5682 D Gabe    : persistState: 16
06-14 08:05:29.542  5652  5652 D Gabe    : persistState: 5
06-14 08:05:34.043  5736  5769 D Gabe    : persistState: 21
```
with `declaredMemberProperties` warming:
```
06-14 08:05:50.617  5865  5916 D Gabe    : persistState: 5
06-14 08:05:50.670  5865  5865 D Gabe    : persistState: 8
06-14 08:05:54.826  5971  6004 D Gabe    : persistState: 9
06-14 08:05:54.981  5971  5971 D Gabe    : persistState: 3
06-14 08:05:59.318  6067  6100 D Gabe    : persistState: 5
06-14 08:05:59.811  6067  6067 D Gabe    : persistState: 5
06-14 08:06:03.791  6149  6185 D Gabe    : persistState: 9
06-14 08:06:04.899  6149  6149 D Gabe    : persistState: 4
06-14 08:06:10.128  6235  6265 D Gabe    : persistState: 5
06-14 08:06:15.794  6318  6351 D Gabe    : persistState: 6
```

Fixes #231

### CODE REVIEW

File: mvrx/src/main/kotlin/com/airbnb/mvrx/BaseMvRxViewModel.kt [hunk 1]
```diff
@@ -41,22 +41,11 @@ abstract class BaseMvRxViewModel<S : MvRxState>(
     private val lastDeliveredStates = ConcurrentHashMap<String, Any>()
     private val activeSubscriptions = Collections.newSetFromMap(ConcurrentHashMap<String, Boolean>())
 
+    internal val state: S
```
Comment (gpeal) [inline mvrx/src/main/kotlin/com/airbnb/mvrx/BaseMvRxViewModel.kt]: I moved this prop above init for style

**Comment by tasomaniac** [comment]
Were you be able to check if this fixes the crash mentioned in #231? Our app starts to crash when R8/Proguard is enabled and I suspect it is because of this change.

I wonder if it is possible to make this change configurable? Users would enable it if they have reflection based performance issues with their usage.

**Comment by gpeal** [comment]
@tasomaniac at Tonal, we're on 1.0.2 and we haven't seen the crash since so I'm going to say that it _probably_ does but I can't say 100% since it's not easily reproducible.

I think every app will have reflection based performance issues since kotlin-reflect init is slow. There is probably a way to fix the R8 issue while leaving this intact. Could you try and get the mvrx sample app to crash by adding R8?

@rossbacher @BenSchwab Any chance you can help out with this as well? It'll block Airbnb from upgrading.
